

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway

  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - authentication-service
      - product-service
      - order-service
      - inventory-service
      - notification-service

  authentication-service:
    build:
      context: ./services/authentication-service
      dockerfile: Dockerfile
    ports:
      - "5005:5005"

  product-service:
    build:
      context: ./services/product-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"

  order-service:
    build:
      context: ./services/order-service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"

  inventory-service:
    build:
      context: ./services/inventory-service
      dockerfile: Dockerfile
    ports:
      - "5003:5003"

  notification-service:
    build:
      context: ./services/notification-service
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
