# application.yml (inside api-gateway service)
spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://product-service:8080
          predicates:
            - Path=/api/products/**

        - id: order-service
          uri: http://order-service:8081
          predicates:
            - Path=/api/orders/**

        - id: inventory-service
          uri: http://inventory-service:8082
          predicates:
            - Path=/api/inventory/**

        - id: notification-service
          uri: http://notification-service:8083
          predicates:
            - Path=/api/notifications/**
