server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/products/**
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/auth/**
